/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class systemcall_cmd_cls_Cls */

#ifndef _Included_systemcall_cmd_cls_Cls
#define _Included_systemcall_cmd_cls_Cls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     systemcall_cmd_cls_Cls
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_systemcall_cmd_cls_Cls_clear
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
