# markdown命令
m:
  b: tools.markdown.MarkdownTools.bold
  l: tools.markdown.MarkdownTools.hyperLinks
  u: tools.markdown.MarkdownTools.unorderList
  o: tools.markdown.MarkdownTools.orderedList
  q: tools.markdown.MarkdownTools.quote
  h1: tools.markdown.MarkdownTools.header1
  h2: tools.markdown.MarkdownTools.header2
  h3: tools.markdown.MarkdownTools.header3
  h4: tools.markdown.MarkdownTools.header4
  h5: tools.markdown.MarkdownTools.header5
  h6: tools.markdown.MarkdownTools.header6
  h+: tools.markdown.MarkdownTools.headerAdd
  h-: tools.markdown.MarkdownTools.headerMinus
  k: tools.markdown.MarkdownTools.inlineCode
  ks: tools.markdown.MarkdownTools.inlineCodeAuto
  nks: tools.markdown.MarkdownTools.inlineCodeUndo
  u2t: formatter.markdown.converter.MardownConverter.unorderList2Table
  o2u: formatter.markdown.converter.MardownConverter.orderList2UnorderList
  u2o: formatter.markdown.converter.MardownConverter.unorderList2OrderList
  f_shuqian111: formatter.string.PdfBookmarkOcrStrCorrector.correctBookmark111
  f_shuqian12: formatter.string.PdfBookmarkOcrStrCorrector.correctBookmark12
  f_shuqian21: formatter.string.PdfBookmarkOcrStrCorrector.correctBookmark21
  f_shuqian211: formatter.string.PdfBookmarkOcrStrCorrector.correctBookmark211
  f_shuqian22: formatter.string.PdfBookmarkOcrStrCorrector.correctBookmark22
  f_shuqian221: formatter.string.PdfBookmarkOcrStrCorrector.correctBookmark221
  dbl: formatter.string.StringDeleter.deleteBlankLine
  ds: formatter.string.StringDeleter.deleteSpaces
  dcb: formatter.string.StringDeleter.deleteMdCodeBlock
  2ol: formatter.string.StringDeleter.deleteCRLF
#  duyin:
  read: xunfei.sst.XunFeiSstFlag.addSSTFlag
  cb:
    j: tools.markdown.MarkdownTools.codeBlockJava
    js: tools.markdown.MarkdownTools.codeBlockJavaScript
  img: tools.markdown.MarkdownTools.img
  table:
    cp: tools.markdown.MarkdownTableTools.mdTableCopy
    cphl: tools.markdown.MarkdownTableTools.mdTableCopyHighlight
    api: tools.markdown.MarkdownTableTools.copyMdTableFramJavadoc
