# markdown代码生成
m:
  # 加粗
  b: tools.markdown.MarkdownTools.bold
  # 超链接
  l: tools.markdown.MarkdownTools.hyperLinks
  # 无序列表
  u: tools.markdown.MarkdownTools.unorderList
  # 有序列表
  o: tools.markdown.MarkdownTools.orderedList
  # 引用
  q: tools.markdown.MarkdownTools.quote
  # 一级标题
  h1: tools.markdown.MarkdownTools.header1
  # 二级标题
  h2: tools.markdown.MarkdownTools.header2
  # 三级标题
  h3: tools.markdown.MarkdownTools.header3
  # 四级标题
  h4: tools.markdown.MarkdownTools.header4
  # 五级标题
  h5: tools.markdown.MarkdownTools.header5
  # 六级标题
  h6: tools.markdown.MarkdownTools.header6
  # 标题降级
  h+: tools.markdown.MarkdownTools.headerAdd
  # 标题升级
  h-: tools.markdown.MarkdownTools.headerMinus
  # 行内代码
  k: tools.markdown.MarkdownTools.inlineCode
  # 多个行内代码
  ks: tools.markdown.MarkdownTools.inlineCodeAuto
  # 水平分割线块，与<hr>标签功能
  hr: tools.markdown.MarkdownTools.horizontalRule
  # 撤销markdown操作
  undo:
    # 撤销多个行内代码操作
    ks: tools.markdown.MarkdownTools.inlineCodeUndo
    # 取消无序列表
    u: tools.markdown.MarkdownTools.cancelUnorderedList
    # 取消markdown加粗
    b: tools.markdown.MarkdownTools.boldUndo
  # 无序列表转表格
  u2t: tools.markdown.MardownConverter.unorderList2Table
  # 有序列表转无序列表
  o2u: tools.markdown.MardownConverter.orderList2UnorderList
  # 无序列表转有序列表
  u2o: tools.markdown.MardownConverter.unorderList2OrderList
  # 行内代码转加粗
  k2b: tools.markdown.MardownConverter.inlineCodeToBold
  # 高亮，对应<mark></mark>标签
  mark: tools.markdown.MarkdownTools.mark
  # markdown代码转成html
  2html:
#    code: tools.markdown.MarkdownTools.toHtmlCode
    # markdown行内代码转成html code标签
    code: tools.markdown.Markdown2Html.toHtmlCode
    # markdown图片转成html img标签
    img: tools.markdown.Markdown2Html.toHtmlImage
  # 图片
  img:
    # markdown图片
    default: tools.markdown.MarkdownTools.img
    # ![xxx](https://g.gravizo.com/svg?<dot代码>)
    dotsvg: tools.markdown.MarkdownTools.imgGravizoSvg
  # 朗读标签
  read: tools.sst.xunfei.XunFeiSstFlag.addSSTFlag
  duyin: tools.sst.xunfei.XunFeiSstFlag.duyin
  # 牛客网行内代码选择题
  niuke:
    # 生成牛客笔记_题目编号自增
    default: tools.markdown.MardownConverter.niuke
    # 生成牛客笔记_重置题目编号
    reset: tools.markdown.MardownConverter.niukeReset
    # 格式化生成的牛客笔记的_行内代码选择题。
    choice: tools.markdown.MardownConverter.niukeInlineCodeChoice
    # 格式化编程题
    programing: tools.markdown.MardownConverter.niukePrograming
  # 代码块
  cb:
    # java代码块
    j:
      # 生成默认代码块
      default: tools.markdown.MarkdownTools.codeBlockJava
      # 生成没有getter和setter方法的java代码块
      ngs: tools.markdown.MdJavaCodeBlock.removeGetterSetterDefaultStyle
    # JavaScript代码块
    js: tools.markdown.MarkdownTools.codeBlockJavaScript
    # sql代码块
    sql: tools.markdown.MarkdownTools.codeBlockSql
    # PlantUML代码块
    plantuml:
      default: tools.markdown.MarkdownTools.codeBlockPlantUml
      # 生成dot语法的PlantUML代码块。
      dot: tools.markdown.MarkdownTools.codeBlockPlantUmlDot
      # 思维导图语法的PlantUML代码块
      mindmap:
        default: tools.markdown.MarkdownTools.codeBlockPlantUmlMindmap
        multiLine:
          default: tools.markdown.MarkdownTools.codeBlockPlantUmlMindmapMultiLine
          code: tools.markdown.MarkdownTools.codeBlockPlantUmlMindmapMultiLineCode
    # default: tools.markdown.MarkdownTools.codeBlockDefault
    default: tools.markdown.MarkdownTools.codeBlock_ControlCodeIsLastArg
  # 删除块中的一些代码
  dcb:
    gsvc: tools.markdown.MdJavaCodeBlock.romoveGetterSetterLikeVC
    gs: tools.markdown.MdJavaCodeBlock.removeGetterSetterDefaultStyle
  # 表格
  table:
    # 将空格分隔的表格格式化为表格
    cp: tools.markdown.JavaDoc2Markdown.mdTableCopy
    # 将空格分隔的表格格式化为表格,并标出代码
    cphl: tools.markdown.JavaDoc2Markdown.mdTableCopyHighlight
    # 将多行分隔的无序列表转成表格
    u: tools.markdown.JavaDoc2Markdown.multiLine2Table
  # 从java API中复制表格转markdown表格
  api:
    # 生成表格
    table:
      # 默认表格
      default: tools.markdown.JavaDoc2Markdown.docMethodTable2MdTable
      # 生成方法表格
      m:
        default: tools.markdown.JavaDoc2Markdown.docMethodTable2MdTable
        nd: tools.markdown.JavaDoc2Markdown.docMethodTable2MdTableNoDescription
      # 只生成表格身体
      b:
        default: tools.markdown.JavaDoc2Markdown.docTable2MdTableBody
        nd: tools.markdown.JavaDoc2Markdown.generateTableBodyNoDescription
      # 属性表格
      f: tools.markdown.JavaDoc2Markdown.docFieldTable2MdTable
    # API中的属性列表
    p2u: tools.markdown.JavaDoc2Markdown.parametersList
  # 修正错误的脚注格式
  footnote: tools.markdown.MarkdownTools.repairFootnoteFormat
  # 从微信读书赋值的有图片或者代码块的多行内容
  weixin:
    # 默认格式化方式
    default: tools.markdown.MarkdownTools.weixinDuShu
    # 本章内容
    bznr: tools.markdown.MarkdownTools.weixinDuShuBenZhangNeiRong
    # 以插图作为标识的无序列表
    u: tools.markdown.MarkdownTools.weixinDuShuUnorderedList
    # 将代码中的中文标点符号替换成对应的英文标点
    code: tools.markdown.MarkdownTools.weixinDuShuCode
# 字符串处理
s:
  delete:
    default: tools.string.StringDeleter.deleteBlankLine
    # 删除空行
    BlankLine: tools.string.StringDeleter.deleteBlankLine
    # 删除中英文之间的空格
    SpacesChEn: tools.string.StringDeleter.deleteSpacesBetweenChineseAndEnglish
  # 删除markdown代码块
  dcb: tools.string.StringDeleter.deleteMdCodeBlock
  # 删除空格
  rmsp: tools.string.StringDeleter.removeSpaces
  # 压缩成一行
  2ol: tools.string.StringDeleter.deleteCRLF
  # 翻译为URL
  tlurl: tools.string.StringConverter.translateToURL
  # 大写
  uc: tools.string.StringConverter.toUpperCase
  # 小写
  lc: tools.string.StringConverter.toLowerCase
  # 首字母小写
  lcf: tools.string.StringConverter.toLowerCaseFirst
  # 首字母大写
  ucf: tools.string.StringConverter.toUpperCaseFirst
  # Linux地址和windows地址相互转换
  cvpath: tools.string.StringConverter.convertFilePath
  # 格式化从微信公众号复制来的代码
  weixincode: tools.string.StringDeleter.weixinCode
  # 修复kindle乱码
  cpkd: tools.string.StringDeleter.cpkd
  # 先修复kindle乱码,然后标出代码。
  cpkdc: tools.string.StringDeleter.cpkdCode
  # 中文标点转英文标点
  cy2ey: tools.string.StringReplace.chineseSymbol2EnglishSymbol
  # 格式化字符串
  format:
    # 格式化为书签
    # x.x.x   类型的书签
    shuqian111: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark111
    # x.xx    类型的书签
    shuqian12: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark12
    # xx.x    类型的书签
    shuqian21: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark21
    # xx.x.x  类型的书签
    shuqian211: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark211
    # xx.xx   类型的书签
    shuqian22: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark22
    # xx.xx.x 类型的书签
    shuqian221: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark221
    # 格式化从pdf中复制的内容
    pdf:
      # 默认格式化功能
      default: tools.string.formatter.PdfFormatter.format
      # 格式化 段落 代码描述 Java代码 这三个混合的文本
      mixed: tools.string.formatter.PdfFormatter.formatPdjMixed
    # P站视频名称:标题+用户名
    ph: tools.string.StringConverter.PHFullVideoName
  # 驼峰命名法
  cc:
    # java包名称
    pn: tools.string.StringConverter.toCameCasePackgeName
    # java类名
    cn: tools.string.StringConverter.toCamelCaseClassName
    # java方法名,属性名
    mn: tools.string.StringConverter.toCameCaseMethodName
    # 取消驼峰命名法
    c: tools.string.StringConverter.cancelCameCase
  # 从文件的绝对路径中 获取文件名
  filename: tools.string.StringDeleter.getFileName
  # 全限定类名
  fqcn: tools.string.StringConverter.fullyQualifiedClassName
  # 全限定xml文件名
  fqxn: tools.string.StringConverter.fullyQualifiedXmlName
  # 格式化微博内容
  fmwb: tools.string.StringConverter.formatWeibo
  # 生成连接手机的adb命令
  adb: tools.string.StringConverter.adb
  # 生成日期字符串：yyyy年MM月dd日
  #  date: tools.string.StringConverter.dateStr_Parameterless
  date: tools.string.StringGenerator.dateStr_Parameterless
  # 打印出字母表
  zimu:
    default: tools.string.StringGenerator.alphabet_Parameterless
  # 字符替换
  replace:
    space:
      underscore: tools.string.StringReplace.characterReplacement_ControlCodeIsLastTwoArgs
    lastTwoDefault: tools.string.StringReplace.characterReplacement_ControlCodeIsLastTwoArgs
# 快捷git命令:当在其他电脑上可能会用到.
g:
  s: git status
  a: git add .
  b: git branch
  ba: git branch -a
  bd: git branch -d
  cm: git commit -m '
  cma: git commit --amend
  d: git diff
  f: git fetch
  fomt: git fetch origin master:tmp
  lpo: git log -10 --pretty=oneline
  lgo: git log --graph --oneline
  m: git merge
  pom: git push origin master
  pos: git push origin src
  pfom: git push -f origin master
  pfos: git push -f origin src
  plom: git pull origin master
  plos: git pull origin src
  r: git restore
  ra: git restore .
  rs: git restore --staged
  rb: git rebase
  rbi: git rebase -i
# html命令
html:
  # 其他命令
  default: tools.html.HtmlTools.htmlDefault_ControlCodeIsLastArg
  # html5模板
  t: templace/html/Html5Template.html
  # html超链接
  a: tools.html.HtmlTools.a
  # 锚点
  ac: tools.html.HtmlTools.anchor
  # html注释
  cm: tools.html.HtmlTools.addComment
  # 讲html注释替换成JSP注释
  2jspcm: tools.html.HtmlTools.htmlComment2JspComment
  # 导入.css的link标签
  link:
    css: tools.html.HtmlTools.linkCss
  # 生成html图片标签
  img: tools.html.HtmlTools.image
  # 导入.js的标签
  js: tools.html.HtmlTools.importJS
  # 展开/折叠块
  fold: tools.html.HtmlTools.flod
  # 展开/折叠块<details>代码
  details:
    # 生成<details>...............</details>代码
    default: tools.html.HtmlTools.details
    # 生成<details><pre>...........</pre></details>
    pre: tools.html.HtmlTools.detailsPre
  # 多行字符串转成html无序列表
  ul: tools.html.HtmlTools.multiLineToUnorderedList
  # 生成<pre></pre>代码块
  pre: tools.html.HtmlTools.pre
  # 替换成转义字符
  es: tools.html.HtmlTools.escape
  # 撤销html转义
  unes: tools.html.HtmlTools.undoEscape
  # 格式化html代码:每个标签占一行
  fl: tools.html.HtmlTools.formatToLine
  # 清理HTML文档中没有必要的属性
  clean: tools.html.HtmlTools.clean
  # HTML代码转Markdown
  2md:
    # HTML文本转换为Markdown文本
    default: tools.html.Html2MarkDown.toMd
    # HTML table单行代码 转markdown table
    table: tools.html.Html2MarkDown.htmlOneLineTable2MdTable
    # 华章在线书籍代码
    hzpc: tools.html.Html2MarkDown.toHuaZhangPreCode
  # 移除html标签，转成纯文本
  2txt: tools.html.HtmlTools.toTxt
  # 生成div标签
  div:
    # 生成div标签
    default: tools.html.HtmlTools.div
    # 生成带边框的div标签
    border:
      # 默认生成带实线边框的div标签
      default: tools.html.HtmlTools.divBorderSolid
      # 生成带 虚线边框 的div标签
      dashed: tools.html.HtmlTools.divBorderDashed
      # 生成带 实线边框 的div标签
      solid: tools.html.HtmlTools.divBorderSolid
      # 生成带 点线边框 的div标签
      dotted: tools.html.HtmlTools.divBorderDotted
      # 生成带 两个边框 的div标签
      double: tools.html.HtmlTools.divBorderDouble
      # 生成带 3D沟槽边框 的div标签
      groove: tools.html.HtmlTools.divBorderGroove
      # 生成带 3D脊边框 的div标签
      gidge: tools.html.HtmlTools.divBorderGidge
      # 生成带 3D的嵌入边框 的div标签
      inset: tools.html.HtmlTools.divBorderInset
      # 生成带 3D突出边框 的div标签
      outset: tools.html.HtmlTools.divBorderOutset
  # 包装js代码成script标签
  script: tools.html.HtmlTools.script
# java代码模板
j:
  # 生成for语句
  for:
    # 遍历字符串的for语句
    str: tools.java.JavaTools.forString
    # 遍历数组的for语句
    arr: tools.java.JavaTools.forArray
  # 生成switch语句
  switch:
    # 生成默认的switch语句
    default: tools.java.JavaTools.switchCaseDefault
    # 生成条件为String的Switch语句
    str: tools.java.JavaTools.switchCaseString
  # 生成System.out.println();
  sout:
    # System.out.println();语句转换成sb.append()语句
    ap: tools.java.JavaTools.sout2Append
  # 格式化代码
  format:
    # 格式化单行注释,把放在末尾的单行注释移动到代码行的上方
    c: tools.java.JavaTools.formatSingleLineComments
    # 格式化mybatis注解的@Results标签
    myrs: tools.java.JavaTools.mybatisResultsFormat
    # 从PDF复制来的代码
    pdf:
      # 格式化从PDF复制来的java代码
      default: tools.java.JavaTools.formatFromPDF
      # 格式化从PDF复制来的字节码
      class: tools.java.JavaTools.formatJavaClassCode
  # 交换参数的顺序(Exchange parameter order)，例如:`int a,int b`交换后变成`int b,int a`
  ecpo: tools.java.JavaTools.exchangeParameterOrder
  # 获取jar包的名称和版本，artifactId version
  jarName: tools.java.JavaTools.jarArtifactIdAndVersion
  # 隐藏方法实现，（Hidden method implementation） `public synchronized boolean contains(Object value) {...}`
  hmi: tools.java.JavaTools.hiddenMethodImplementation
  # Eclipse java代码辅助 自动补全，设置
  自动补全: tools.string.StringGenerator.javaCodeAssist_Parameterless
# 算法
suanfa:
  # 冒泡排序
  maopao:
    js: templace/algorithm/sort/js/BubbleSort.js
    default: templace/algorithm/sort/java/BubbleSort.java
  # 鸡尾酒排序
  jiweijiu: templace/algorithm/sort/java/CockTailSort.java
  # 选择排序
  xuanzhe: templace/algorithm/sort/java/SelectionSort.java
  # 插入排序
  charu: templace/algorithm/sort/java/InsertSort.java
  # 希尔排序
  xier: templace/algorithm/sort/java/ShellSort.java
  # 转换成QQ输入法的多行个性短语
  2qq:
    # 转换成QQ输入法的多行个性短语
    default: tools.string.StringReplace.qqShuRuFa
    # 转换成QQ输入法的注释
    c: tools.string.StringReplace.qqShuRuFaZhuShi
# LaTeX公式
latex:
  # 默认生成行内公式
  default: tools.markdown.math.LaTeX.s
  # 生成行内公式
  s: tools.markdown.math.LaTeX.s
  # 生成行间公式
  ss: tools.markdown.math.LaTeX.ss

hexo:
  frontmatter:
    # 生成FrontMatter
    default: tools.markdown.hexo.frontmatter.FrontMatterGenerator.doOneArgIsFilePath
    # 生成exam站点定制的FrontMatter
    exam: tools.markdown.hexo.frontmatter.FrontMatterGenerator.doOneArgIsExam
    addJS: tools.markdown.hexo.frontmatter.FrontMatterGenerator.addMyHexoFrontMatter
  # 生成站点目录文件
  toc:
    # 使用剪贴板中的内容作为方法的输入
    clipboard: tools.markdown.hexo.frontmatter.FrontMatterGenerator.siteTOC
    # defalut: tools.markdown.hexo.frontmatter.FrontMatterGenerator.siteTOC
    # 使用最后一个命令行参数作为方法的输入
    default: tools.markdown.hexo.frontmatter.FrontMatterGenerator.siteTOC_LastArgIsMethodInput
    # # default: tools.markdown.MarkdownTools.codeBlockDefault
    # default: tools.markdown.MarkdownTools.codeBlock_ControlCodeIsLastArg