# markdown代码生成
m:
  # 加粗
  b: tools.markdown.MarkdownTools.bold
  # 超链接
  l: tools.markdown.MarkdownTools.hyperLinks
  # 无序列表
  u: tools.markdown.MarkdownTools.unorderList
  # 有序列表
  o: tools.markdown.MarkdownTools.orderedList
  # 引用
  q: tools.markdown.MarkdownTools.quote
  # 一级标题
  h1: tools.markdown.MarkdownTools.header1
  h2: tools.markdown.MarkdownTools.header2
  h3: tools.markdown.MarkdownTools.header3
  h4: tools.markdown.MarkdownTools.header4
  h5: tools.markdown.MarkdownTools.header5
  h6: tools.markdown.MarkdownTools.header6
  # 标题降级
  h+: tools.markdown.MarkdownTools.headerAdd
  # 标题升级
  h-: tools.markdown.MarkdownTools.headerMinus
  # 行内代码
  k: tools.markdown.MarkdownTools.inlineCode
  # 多个行内代码
  ks: tools.markdown.MarkdownTools.inlineCodeAuto
  # 移除行内代码
  nks: tools.markdown.MarkdownTools.inlineCodeUndo
  # 无序列表转表格
  u2t: tools.markdown.MardownConverter.unorderList2Table
  # 有序列表转无序列表
  o2u: tools.markdown.MardownConverter.orderList2UnorderList
  # 无序列表转有序列表
  u2o: tools.markdown.MardownConverter.unorderList2OrderList
  # 行内代码转加粗
  k2b: tools.markdown.MardownConverter.inlineCodeToBold
  # 图片
  img: tools.markdown.MarkdownTools.img
  read: tools.sst.xunfei.XunFeiSstFlag.addSSTFlag
  duyin: tools.sst.xunfei.XunFeiSstFlag.duyin
  # 代码块
  cb:
    j:
      default: tools.markdown.MarkdownTools.codeBlockJava
      ngs: tools.markdown.MdJavaCodeBlock.removeGetterSetterDefaultStyle
    js: tools.markdown.MarkdownTools.codeBlockJavaScript
    sql: tools.markdown.MarkdownTools.codeBlockSql
    # default: tools.markdown.MarkdownTools.codeBlockDefault
    default: tools.markdown.MarkdownTools.codeBlock_UseLastArg
  # 删除块中的一些代码
  dcb:
    gsvc: tools.markdown.MdJavaCodeBlock.romoveGetterSetterLikeVC
    gs: tools.markdown.MdJavaCodeBlock.removeGetterSetterDefaultStyle
  # 表格
  table:
    # 将空格分隔的表格格式化为表格
    cp: tools.markdown.JavaDoc2Markdown.mdTableCopy
    # 将空格分隔的表格格式化为表格,并标出代码
    cphl: tools.markdown.JavaDoc2Markdown.mdTableCopyHighlight
    # 将多行分隔的无序列表转成表格
    u: tools.markdown.JavaDoc2Markdown.multiLine2Table
  # 从java API中复制
  api:
    table:
      default: tools.markdown.JavaDoc2Markdown.docMethodTable2MdTable
      m:
        default: tools.markdown.JavaDoc2Markdown.docMethodTable2MdTable
        nd: tools.markdown.JavaDoc2Markdown.docMethodTable2MdTableNoDescription
      b:
        default: tools.markdown.JavaDoc2Markdown.docTable2MdTableBody
        nd: tools.markdown.JavaDoc2Markdown.generateTableBodyNoDescription
      f: tools.markdown.JavaDoc2Markdown.docFieldTable2MdTable
    p2u: tools.markdown.JavaDoc2Markdown.parametersList
# 字符串处理
s:
  # 删除空行
  dbl: tools.string.StringDeleter.deleteBlankLine
  # 删除多余空白符
  dsbc: tools.string.StringDeleter.deleteSpaces
  # 删除markdown代码块
  dcb: tools.string.StringDeleter.deleteMdCodeBlock
  # 删除空格
  rmsp: tools.string.StringDeleter.removeSpaces
  # 压缩成一行
  2ol: tools.string.StringDeleter.deleteCRLF
  # 翻译为URL
  tlurl: tools.string.StringConverter.translateToURL
  # 大写
  uc: tools.string.StringConverter.toUppperCase
  # 小写
  lc: tools.string.StringConverter.toLowerCase
  # 首字母小写
  lcf: tools.string.StringConverter.toLowerCaseFirst
  # 首字母大写
  ucf: tools.string.StringConverter.toUpperCaseFirst
  # java包名称
  2ccpn: tools.string.StringConverter.toCameCasePackgeName
  # 驼峰命名法java类名
  2cccn: tools.string.StringConverter.toCamelCaseClassName
  # 驼峰命名法java方法名,属性名
  2ccmn: tools.string.StringConverter.toCameCaseMethodName
  # Linux地址和windows地址相互转换
  cvpath: tools.string.StringConverter.convertFilePath
  # 格式化从微信公众号复制来的代码
  weixincode: tools.string.StringDeleter.weixinCode
  # 修复kindle乱码
  cpkd: tools.string.StringDeleter.cpkd
  # 先修复kindle乱码,然后标出代码。
  cpkdc: tools.string.StringDeleter.cpkdCode
  # 中文标点转英文标点
  cy2ey: tools.string.StringReplace.chineseSymbol2EnglishSymbol
  f:
    shuqian111: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark111
    shuqian12: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark12
    shuqian21: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark21
    shuqian211: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark211
    shuqian22: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark22
    shuqian221: tools.string.PdfBookmarkOcrStrCorrector.correctBookmark221
# 快捷git命令:当在其他电脑上可能会用到.
g:
  s: git status
  a: git add .
  b: git branch
  ba: git branch -a
  bd: git branch -d
  cm: git commit -m '
  cma: git commit --amend
  d: git diff
  f: git fetch
  fomt: git fetch origin master:tmp
  lpo: git log -10 --pretty=oneline
  lgo: git log --graph --oneline
  m: git merge
  pom: git push origin master
  pos: git push origin src
  pfom: git push -f origin master
  pfos: git push -f origin src
  plom: git pull origin master
  plos: git pull origin src
  r: git restore
  ra:  git restore .
  rs: git restore --staged
  rb: git rebase
  rbi: git rebase -i
# html命令
h:
  # 其他命令
  default: tools.html.HtmlTools.htmlDefault_UseLastArg
  # html5模板
  t: templace/html/Html5Template.html
  # html超链接
  a: tools.html.HtmlTools.a
  # 锚点
  ac: tools.html.HtmlTools.anchor
  # html注释
  cm: tools.html.HtmlTools.addComment
  # 导入.css的link标签
  linkcss: tools.html.HtmlTools.linkCss
  # 导入.js的标签
  js: tools.html.HtmlTools.importJS
  # 展开/折叠块
  fold: tools.html.HtmlTools.flod
  dp: tools.html.HtmlTools.detailsPre
  # 多行字符串转成html无序列表
  ul: tools.html.HtmlTools.unorderedList
  # 生成<pre></pre>代码块
  pre: tools.html.HtmlTools.pre
  # 替换成转义字符
  es: tools.html.HtmlTools.escape
# java代码模板
j:
  for:
    # 遍历字符串的for语句
    str: tools.java.JavaTools.forString
    # 遍历数组的for语句
    arr: tools.java.JavaTools.forArray
  # 生成switch语句
  switch:
    default: tools.java.JavaTools.switchCaseDefault
    str: tools.java.JavaTools.switchCaseString
  sout:
    ap: tools.java.JavaTools.sout2Append
# 算法
suanfa:
  # 冒泡排序
  maopao:
    js: templace/algorithm/sort/js/BubbleSort.js
    default: templace/algorithm/sort/java/BubbleSort.java
  # 鸡尾酒排序
  jiweijiu: templace/algorithm/sort/java/CockTailSort.java
  # 选择排序
  xuanzhe: templace/algorithm/sort/java/SelectionSort.java
  # 插入排序
  charu: templace/algorithm/sort/java/InsertSort.java
  # 希尔排序
  xier: templace/algorithm/sort/java/ShellSort.java
